create database sri;
DROP TABLE EMPLOYEE;

create table EMPLOYEE1(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
SALARY INT,
DESIGNATION VARCHAR(50)


);

ALTER TABLE EMPLOYEE ADD BRANCH VARCHAR (20);
ALTER TABLE EMPLOYEE DROP COLUMN BRANCH;

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE1 VALUES (ID,'NAME',SALARY,'DESIGNATION');



SELECT NAME FROM EMPLOYEE
WHERE SALARY <20000 AND DESIGNATION = 'HR'

SELECT * FROM EMPLOYEE
WHERE NAME LIKE '__B%';


SELECT *FROM EMPLOYEE
ORDER BY ( CASE DESIGNATION
WHEN 'CEO' THEN 1
WHEN 'HR' THEN 2
ELSE 100 END);


SELECT * FROM EMPLOYEE
SELECT MAX (SALARY)AS RESULT
FROM EMPLOYEE;

WHERE DESIGNATION  ='HR'
ORDER BY SALARY;



INSERT INTO EMPLOYEE1 VALUES (2,'BBI',10000,'ADMIN');

INSERT INTO EMPLOYEE1 VALUES (3,'CBI',105000,'CEO');
INSERT INTO EMPLOYEE1 VALUES (4,'DBI',610000,'MANAGER');
INSERT INTO EMPLOYEE VALUES (5,'EBI',170000,'DEVELOPER');
INSERT INTO EMPLOYEE VALUES (6,'FBI',1340000,'TEAM LEAD');
INSERT INTO EMPLOYEE VALUES (7,'GBI',1110000,'CEO');
INSERT INTO EMPLOYEE VALUES (8,'HBI',130000,'DEVELOPER');
INSERT INTO EMPLOYEE VALUES (9,'IBI',910000,'HR');

INSERT INTO EMPLOYEE VALUES (10,'JBI',710000,'DESIGNER');

INSERT INTO EMPLOYEE VALUES (11,'KBI',150000,'TESTER');
INSERT INTO EMPLOYEE VALUES (12,'LBI',210000,'MANAGER');
INSERT INTO EMPLOYEE VALUES (13,'MBI',120000,'SECURITY');
INSERT INTO EMPLOYEE VALUES (14,'NBI',106000,'ACCOUNTANT');
INSERT INTO EMPLOYEE VALUES (15,'OBI',105000,'ADMIN');

INSERT INTO EMPLOYEE (ID,NAME)VALUES(16,'TABI');

SELECT ID, NAME FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES (17,'OBI',105000,'ADMIN'),(18,'RBI',20000,'HR');

 SELECT SUM (SALARY) AS RESULT
 FROM EMPLOYEE WHERE SALARY>100000 ;

 SELECT COUNT (NAME) FROM EMPLOYEE;
 SELECT COUNT(*) NAS
 FROM EMPLOYEE;

 CREATE TABLE STUDENT(
 ID INT NOT NULL,
 NAME VARCHAR (30)NOT NULL,
 CITY VARCHAR(20)
 );
 SELECT * FROM STUDENT;


 ALTER TABLE STUDENT
 ADD AGE INT NOT NULL;
 INSERT INTO STUDENT VALUES(1, 'SRI','CHENNAI');
  INSERT INTO STUDENT VALUES( 'SRI','CHENNAI');

  SELECT * FROM EMPLOYEE;

  UPDATE EMPLOYEE
  SET SALARY = '1250000'
  WHERE ID = 2;

  UPDATE EMPLOYEE
  SET NAME = 'SARA' , DESIGNATION = 'HR'
  WHERE ID = 2;

  DELETE FROM EMPLOYEE
  WHERE ID= 3;


  --CREATE INDEX--

  CREATE INDEX MYINDEX ON EMPLOYEE(NAME);

  ALTER TABLE EMPLOYEE
  DROP INDEX MYINDEX;
  SELECT MAX (SALARY)
  FROM EMPLOYEE;

  SELECT UPPERCASE (NAME),SALARY
  FROM EMPLOYEE;


  SELECT NAME,CONCAT('RS.',FORMAT (SALARY,0))
  FROM EMPLOYEE;

  SELECT NAME, LEFT (DESIGNATION,3)
  FROM EMPLOYEE;

   ALTER TABLE EMPLOYEE ADD COLUMN HIRE_DATE;

SELECT DESIGNATION, AVG (SALARY)
FROM EMPLOYEE
GROUP BY DESIGNATION;


SELECT DESIGNATION, COUNT(ID)
FROM EMPLOYEE
WHERE SALARY> 100000
GROUP BY DESIGNATION
HAVING COUNT (ID)>1
ORDER BY DESIGNATION;	

CREATE TABLE CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY,
CNAME VARCHAR(30) NOT NULL,
BRANCH VARCHAR (40) DEFAULT 'UNASSIGNED',
SALARY INT,
PAN VARCHAR (10) UNIQUE,
CHECK (SALARY >10000)
);

SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES (2, 'NAMGA',' CHEBPBAI', 1000, 'GYRUP234');

ALTER TABLE CUSTOMER

DROP COLUMN CNAME FROM CUSTOMER;
DROP TABLE CUSTOMER;

create table EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
SALARY INT,
DESIGNATION VARCHAR(50));

DROP TABLE EMPLOYEE;

CREATE TABLE BRANCH(
BRANCH_ID INT PRIMARY KEY,
BR_NAME VARCHAR(30),
ADDR VARCHAR(200));


create table EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
SALARY INT,
DESIGNATION VARCHAR(50),
BRANCH_ID INT,
CONSTRAINT FK_BRANCHID FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH (BRANCH_ID)
);

SELECT EMPLOYEE.ID,EMPLOYEE.NAME, EMPLOYEE.SALARY,BRANCH.BR_NAME
FROM EMPLOYEE
JOIN BRANCH
ON EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID;

INSERT INTO BRANCH VALUES (1,'CHENNAI','12 ADDRE');
SELECT * FROM BRANCH

INSERT INTO EMPLOYEE VALUES (1,'ABI',10000,'HR',2);

CREATE TABLE CLIENT(
CLIENT_ID INT PRIMARY KEY,
LOCATION VARCHAR(40),
ADDR VARCHAR (20));


INSERT INTO CLIENT VALUES (1,'NEWYORK','25 10TH BLOCK');
SELECT * FROM CLIENT

SELECT * FROM BRANCH
UNION ALL
SELECT * FROM 


SELECT * FROM EMPLOYEE1;

SELECT SALARY FROM EMPLOYEE1
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE1);

SELECT BRANCH_ID,BR_NAME
FROM BRANCH
WHERE EXISTS(
SELECT * FROM EMPLOYEE
WHERE DESIGNATION= 'HR' AND BRANCH.BRANCH_ID=EMPLOYEE.BRANCH_ID);



select * from EMPLOYEE1

ORDER BY DESIGNATION;

SELECT TOP 2* FROM EMPLOYEE1
ORDER BY SALARY;

DELETE FROM EMPLOYEE1;

SELECT COUNT (DESIGNATION) NUMBER
FROM EMPLOYEE1;



CREATE TABLE ORDERS;




create table EMPLOYEE;


SELECT * FROM EMPLOYEE1;

SELECT * FROM EMPLOYEE1 
WHERE DESIGNATION LIKE '%M%';